{% set name = "onnx" %}
{% set version = "1.16.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  git_url: "https://github.com/onnx/onnx.git"
  git_rev: v{{ version }}

build:
  number: 2
  string: h{{ PKG_HASH }}_py{{ python | replace(".", "") }}_pb{{ protobuf | replace(".*", "")}}_{{ PKG_BUILDNUM }}
  entry_points:
    - check-model = onnx.bin.checker:check_model
    - check-node = onnx.bin.checker:check_node
    - backend-test-tools = onnx.backend.test.cmd_tools:main
  script_env:                 # [ppc_arch == "p10"]
    - GCC_HOME             # [ppc_arch == "p10"]

requirements:
  build:
    - {{ compiler('c') }}     # [ppc_arch != "p10"]
    - {{ compiler('cxx') }}   # [ppc_arch != "p10"]
    - cmake {{ cmake }}
    - make                # needed by cmake
    - libprotobuf {{ libprotobuf }}
  host:
    - python {{ python }}
    - pip
    - protobuf {{ protobuf }}
    - libprotobuf {{ libprotobuf }}
    - pytest-runner
    - ninja {{ ninja }}

  run:
    - python {{ python }}
    - protobuf {{ protobuf }}
    - libprotobuf {{ libprotobuf }}
    - numpy {{ numpy }}
    - six {{ six }}
    - typing-extensions {{ typing_extensions }}

test:
  imports:
    - onnx
  commands:
    - check-model --help
    - check-node --help
    - backend-test-tools --help

about:
  home: https://github.com/onnx/onnx/
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Open Neural Network Exchange library
  description: |
    Open Neural Network Exchange (ONNX) is the first step toward an open
    ecosystem that empowers AI developers to choose the right tools as their
    project evolves. ONNX provides an open source format for AI models. It
    defines an extensible computation graph model, as well as definitions of
    built-in operators and standard data types. Initially we focus on the
    capabilities needed for inferencing (evaluation).

extra:
  recipe-maintainers:
    - open-ce/open-ce-dev-team
